/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedRouteImport } from './routes/red'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as ParaMiRouteImport } from './routes/para-mi'
import { Route as ParaAyudarRouteImport } from './routes/para-ayudar'
import { Route as FuentesRouteImport } from './routes/fuentes'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as AyudaRouteImport } from './routes/ayuda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ParaMiIndexRouteImport } from './routes/para-mi.index'
import { Route as ParaAyudarIndexRouteImport } from './routes/para-ayudar.index'
import { Route as ParaMiRespiraRouteImport } from './routes/para-mi.respira'
import { Route as ParaMiReplicasRouteImport } from './routes/para-mi.replicas'
import { Route as ParaMiPresenteRouteImport } from './routes/para-mi.presente'
import { Route as ParaMiPerdisteTodoRouteImport } from './routes/para-mi.perdiste-todo'
import { Route as ParaMiNoticiasRouteImport } from './routes/para-mi.noticias'
import { Route as ParaMiNormalRouteImport } from './routes/para-mi.normal'
import { Route as ParaMiNoEncontradoRouteImport } from './routes/para-mi.no-encontrado'
import { Route as ParaMiLejosRouteImport } from './routes/para-mi.lejos'
import { Route as ParaMiDueloRouteImport } from './routes/para-mi.duelo'
import { Route as ParaMiDiarioRouteImport } from './routes/para-mi.diario'
import { Route as ParaMiDescansarRouteImport } from './routes/para-mi.descansar'
import { Route as ParaMiComoEstasRouteImport } from './routes/para-mi.como-estas'
import { Route as ParaAyudarQueDecirRouteImport } from './routes/para-ayudar.que-decir'
import { Route as ParaAyudarPanicoRouteImport } from './routes/para-ayudar.panico'
import { Route as ParaAyudarNoMejoraRouteImport } from './routes/para-ayudar.no-mejora'
import { Route as ParaAyudarNinoRouteImport } from './routes/para-ayudar.nino'
import { Route as ParaAyudarEntrenamientoRouteImport } from './routes/para-ayudar.entrenamiento'
import { Route as ParaAyudarAhoraRouteImport } from './routes/para-ayudar.ahora'
import { Route as ParaAyudarAdultoMayorRouteImport } from './routes/para-ayudar.adulto-mayor'
import { Route as ParaAyudarADistanciaRouteImport } from './routes/para-ayudar.a-distancia'
import { Route as ParaAyudarEntrenamientoIndexRouteImport } from './routes/para-ayudar.entrenamiento.index'
import { Route as ParaAyudarEntrenamientoMidRouteImport } from './routes/para-ayudar.entrenamiento.$mid'

const RedRoute = RedRouteImport.update({
  id: '/red',
  path: '/red',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaMiRoute = ParaMiRouteImport.update({
  id: '/para-mi',
  path: '/para-mi',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaAyudarRoute = ParaAyudarRouteImport.update({
  id: '/para-ayudar',
  path: '/para-ayudar',
  getParentRoute: () => rootRouteImport,
} as any)
const FuentesRoute = FuentesRouteImport.update({
  id: '/fuentes',
  path: '/fuentes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const AyudaRoute = AyudaRouteImport.update({
  id: '/ayuda',
  path: '/ayuda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaMiIndexRoute = ParaMiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParaMiRoute,
} as any)
const ParaAyudarIndexRoute = ParaAyudarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParaAyudarRoute,
} as any)
const ParaMiRespiraRoute = ParaMiRespiraRouteImport.update({
  id: '/respira',
  path: '/respira',
  getParentRoute: () => ParaMiRoute,
} as any)
const ParaMiReplicasRoute = ParaMiReplicasRouteImport.update({
  id: '/replicas',
  path: '/replicas',
  getParentRoute: () => ParaMiRoute,
} as any)
const ParaMiPresenteRoute = ParaMiPresenteRouteImport.update({
  id: '/presente',
  path: '/presente',
  getParentRoute: () => ParaMiRoute,
} as any)
const ParaMiPerdisteTodoRoute = ParaMiPerdisteTodoRouteImport.update({
  id: '/perdiste-todo',
  path: '/perdiste-todo',
  getParentRoute: () => ParaMiRoute,
} as any)
const ParaMiNoticiasRoute = ParaMiNoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => ParaMiRoute,
} as any)
const ParaMiNormalRoute = ParaMiNormalRouteImport.update({
  id: '/normal',
  path: '/normal',
  getParentRoute: () => ParaMiRoute,
} as any)
const ParaMiNoEncontradoRoute = ParaMiNoEncontradoRouteImport.update({
  id: '/no-encontrado',
  path: '/no-encontrado',
  getParentRoute: () => ParaMiRoute,
} as any)
const ParaMiLejosRoute = ParaMiLejosRouteImport.update({
  id: '/lejos',
  path: '/lejos',
  getParentRoute: () => ParaMiRoute,
} as any)
const ParaMiDueloRoute = ParaMiDueloRouteImport.update({
  id: '/duelo',
  path: '/duelo',
  getParentRoute: () => ParaMiRoute,
} as any)
const ParaMiDiarioRoute = ParaMiDiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => ParaMiRoute,
} as any)
const ParaMiDescansarRoute = ParaMiDescansarRouteImport.update({
  id: '/descansar',
  path: '/descansar',
  getParentRoute: () => ParaMiRoute,
} as any)
const ParaMiComoEstasRoute = ParaMiComoEstasRouteImport.update({
  id: '/como-estas',
  path: '/como-estas',
  getParentRoute: () => ParaMiRoute,
} as any)
const ParaAyudarQueDecirRoute = ParaAyudarQueDecirRouteImport.update({
  id: '/que-decir',
  path: '/que-decir',
  getParentRoute: () => ParaAyudarRoute,
} as any)
const ParaAyudarPanicoRoute = ParaAyudarPanicoRouteImport.update({
  id: '/panico',
  path: '/panico',
  getParentRoute: () => ParaAyudarRoute,
} as any)
const ParaAyudarNoMejoraRoute = ParaAyudarNoMejoraRouteImport.update({
  id: '/no-mejora',
  path: '/no-mejora',
  getParentRoute: () => ParaAyudarRoute,
} as any)
const ParaAyudarNinoRoute = ParaAyudarNinoRouteImport.update({
  id: '/nino',
  path: '/nino',
  getParentRoute: () => ParaAyudarRoute,
} as any)
const ParaAyudarEntrenamientoRoute = ParaAyudarEntrenamientoRouteImport.update({
  id: '/entrenamiento',
  path: '/entrenamiento',
  getParentRoute: () => ParaAyudarRoute,
} as any)
const ParaAyudarAhoraRoute = ParaAyudarAhoraRouteImport.update({
  id: '/ahora',
  path: '/ahora',
  getParentRoute: () => ParaAyudarRoute,
} as any)
const ParaAyudarAdultoMayorRoute = ParaAyudarAdultoMayorRouteImport.update({
  id: '/adulto-mayor',
  path: '/adulto-mayor',
  getParentRoute: () => ParaAyudarRoute,
} as any)
const ParaAyudarADistanciaRoute = ParaAyudarADistanciaRouteImport.update({
  id: '/a-distancia',
  path: '/a-distancia',
  getParentRoute: () => ParaAyudarRoute,
} as any)
const ParaAyudarEntrenamientoIndexRoute =
  ParaAyudarEntrenamientoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ParaAyudarEntrenamientoRoute,
  } as any)
const ParaAyudarEntrenamientoMidRoute =
  ParaAyudarEntrenamientoMidRouteImport.update({
    id: '/$mid',
    path: '/$mid',
    getParentRoute: () => ParaAyudarEntrenamientoRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ayuda': typeof AyudaRoute
  '/contacto': typeof ContactoRoute
  '/fuentes': typeof FuentesRoute
  '/para-ayudar': typeof ParaAyudarRouteWithChildren
  '/para-mi': typeof ParaMiRouteWithChildren
  '/privacidad': typeof PrivacidadRoute
  '/red': typeof RedRoute
  '/para-ayudar/a-distancia': typeof ParaAyudarADistanciaRoute
  '/para-ayudar/adulto-mayor': typeof ParaAyudarAdultoMayorRoute
  '/para-ayudar/ahora': typeof ParaAyudarAhoraRoute
  '/para-ayudar/entrenamiento': typeof ParaAyudarEntrenamientoRouteWithChildren
  '/para-ayudar/nino': typeof ParaAyudarNinoRoute
  '/para-ayudar/no-mejora': typeof ParaAyudarNoMejoraRoute
  '/para-ayudar/panico': typeof ParaAyudarPanicoRoute
  '/para-ayudar/que-decir': typeof ParaAyudarQueDecirRoute
  '/para-mi/como-estas': typeof ParaMiComoEstasRoute
  '/para-mi/descansar': typeof ParaMiDescansarRoute
  '/para-mi/diario': typeof ParaMiDiarioRoute
  '/para-mi/duelo': typeof ParaMiDueloRoute
  '/para-mi/lejos': typeof ParaMiLejosRoute
  '/para-mi/no-encontrado': typeof ParaMiNoEncontradoRoute
  '/para-mi/normal': typeof ParaMiNormalRoute
  '/para-mi/noticias': typeof ParaMiNoticiasRoute
  '/para-mi/perdiste-todo': typeof ParaMiPerdisteTodoRoute
  '/para-mi/presente': typeof ParaMiPresenteRoute
  '/para-mi/replicas': typeof ParaMiReplicasRoute
  '/para-mi/respira': typeof ParaMiRespiraRoute
  '/para-ayudar/': typeof ParaAyudarIndexRoute
  '/para-mi/': typeof ParaMiIndexRoute
  '/para-ayudar/entrenamiento/$mid': typeof ParaAyudarEntrenamientoMidRoute
  '/para-ayudar/entrenamiento/': typeof ParaAyudarEntrenamientoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ayuda': typeof AyudaRoute
  '/contacto': typeof ContactoRoute
  '/fuentes': typeof FuentesRoute
  '/privacidad': typeof PrivacidadRoute
  '/red': typeof RedRoute
  '/para-ayudar/a-distancia': typeof ParaAyudarADistanciaRoute
  '/para-ayudar/adulto-mayor': typeof ParaAyudarAdultoMayorRoute
  '/para-ayudar/ahora': typeof ParaAyudarAhoraRoute
  '/para-ayudar/nino': typeof ParaAyudarNinoRoute
  '/para-ayudar/no-mejora': typeof ParaAyudarNoMejoraRoute
  '/para-ayudar/panico': typeof ParaAyudarPanicoRoute
  '/para-ayudar/que-decir': typeof ParaAyudarQueDecirRoute
  '/para-mi/como-estas': typeof ParaMiComoEstasRoute
  '/para-mi/descansar': typeof ParaMiDescansarRoute
  '/para-mi/diario': typeof ParaMiDiarioRoute
  '/para-mi/duelo': typeof ParaMiDueloRoute
  '/para-mi/lejos': typeof ParaMiLejosRoute
  '/para-mi/no-encontrado': typeof ParaMiNoEncontradoRoute
  '/para-mi/normal': typeof ParaMiNormalRoute
  '/para-mi/noticias': typeof ParaMiNoticiasRoute
  '/para-mi/perdiste-todo': typeof ParaMiPerdisteTodoRoute
  '/para-mi/presente': typeof ParaMiPresenteRoute
  '/para-mi/replicas': typeof ParaMiReplicasRoute
  '/para-mi/respira': typeof ParaMiRespiraRoute
  '/para-ayudar': typeof ParaAyudarIndexRoute
  '/para-mi': typeof ParaMiIndexRoute
  '/para-ayudar/entrenamiento/$mid': typeof ParaAyudarEntrenamientoMidRoute
  '/para-ayudar/entrenamiento': typeof ParaAyudarEntrenamientoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ayuda': typeof AyudaRoute
  '/contacto': typeof ContactoRoute
  '/fuentes': typeof FuentesRoute
  '/para-ayudar': typeof ParaAyudarRouteWithChildren
  '/para-mi': typeof ParaMiRouteWithChildren
  '/privacidad': typeof PrivacidadRoute
  '/red': typeof RedRoute
  '/para-ayudar/a-distancia': typeof ParaAyudarADistanciaRoute
  '/para-ayudar/adulto-mayor': typeof ParaAyudarAdultoMayorRoute
  '/para-ayudar/ahora': typeof ParaAyudarAhoraRoute
  '/para-ayudar/entrenamiento': typeof ParaAyudarEntrenamientoRouteWithChildren
  '/para-ayudar/nino': typeof ParaAyudarNinoRoute
  '/para-ayudar/no-mejora': typeof ParaAyudarNoMejoraRoute
  '/para-ayudar/panico': typeof ParaAyudarPanicoRoute
  '/para-ayudar/que-decir': typeof ParaAyudarQueDecirRoute
  '/para-mi/como-estas': typeof ParaMiComoEstasRoute
  '/para-mi/descansar': typeof ParaMiDescansarRoute
  '/para-mi/diario': typeof ParaMiDiarioRoute
  '/para-mi/duelo': typeof ParaMiDueloRoute
  '/para-mi/lejos': typeof ParaMiLejosRoute
  '/para-mi/no-encontrado': typeof ParaMiNoEncontradoRoute
  '/para-mi/normal': typeof ParaMiNormalRoute
  '/para-mi/noticias': typeof ParaMiNoticiasRoute
  '/para-mi/perdiste-todo': typeof ParaMiPerdisteTodoRoute
  '/para-mi/presente': typeof ParaMiPresenteRoute
  '/para-mi/replicas': typeof ParaMiReplicasRoute
  '/para-mi/respira': typeof ParaMiRespiraRoute
  '/para-ayudar/': typeof ParaAyudarIndexRoute
  '/para-mi/': typeof ParaMiIndexRoute
  '/para-ayudar/entrenamiento/$mid': typeof ParaAyudarEntrenamientoMidRoute
  '/para-ayudar/entrenamiento/': typeof ParaAyudarEntrenamientoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ayuda'
    | '/contacto'
    | '/fuentes'
    | '/para-ayudar'
    | '/para-mi'
    | '/privacidad'
    | '/red'
    | '/para-ayudar/a-distancia'
    | '/para-ayudar/adulto-mayor'
    | '/para-ayudar/ahora'
    | '/para-ayudar/entrenamiento'
    | '/para-ayudar/nino'
    | '/para-ayudar/no-mejora'
    | '/para-ayudar/panico'
    | '/para-ayudar/que-decir'
    | '/para-mi/como-estas'
    | '/para-mi/descansar'
    | '/para-mi/diario'
    | '/para-mi/duelo'
    | '/para-mi/lejos'
    | '/para-mi/no-encontrado'
    | '/para-mi/normal'
    | '/para-mi/noticias'
    | '/para-mi/perdiste-todo'
    | '/para-mi/presente'
    | '/para-mi/replicas'
    | '/para-mi/respira'
    | '/para-ayudar/'
    | '/para-mi/'
    | '/para-ayudar/entrenamiento/$mid'
    | '/para-ayudar/entrenamiento/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ayuda'
    | '/contacto'
    | '/fuentes'
    | '/privacidad'
    | '/red'
    | '/para-ayudar/a-distancia'
    | '/para-ayudar/adulto-mayor'
    | '/para-ayudar/ahora'
    | '/para-ayudar/nino'
    | '/para-ayudar/no-mejora'
    | '/para-ayudar/panico'
    | '/para-ayudar/que-decir'
    | '/para-mi/como-estas'
    | '/para-mi/descansar'
    | '/para-mi/diario'
    | '/para-mi/duelo'
    | '/para-mi/lejos'
    | '/para-mi/no-encontrado'
    | '/para-mi/normal'
    | '/para-mi/noticias'
    | '/para-mi/perdiste-todo'
    | '/para-mi/presente'
    | '/para-mi/replicas'
    | '/para-mi/respira'
    | '/para-ayudar'
    | '/para-mi'
    | '/para-ayudar/entrenamiento/$mid'
    | '/para-ayudar/entrenamiento'
  id:
    | '__root__'
    | '/'
    | '/ayuda'
    | '/contacto'
    | '/fuentes'
    | '/para-ayudar'
    | '/para-mi'
    | '/privacidad'
    | '/red'
    | '/para-ayudar/a-distancia'
    | '/para-ayudar/adulto-mayor'
    | '/para-ayudar/ahora'
    | '/para-ayudar/entrenamiento'
    | '/para-ayudar/nino'
    | '/para-ayudar/no-mejora'
    | '/para-ayudar/panico'
    | '/para-ayudar/que-decir'
    | '/para-mi/como-estas'
    | '/para-mi/descansar'
    | '/para-mi/diario'
    | '/para-mi/duelo'
    | '/para-mi/lejos'
    | '/para-mi/no-encontrado'
    | '/para-mi/normal'
    | '/para-mi/noticias'
    | '/para-mi/perdiste-todo'
    | '/para-mi/presente'
    | '/para-mi/replicas'
    | '/para-mi/respira'
    | '/para-ayudar/'
    | '/para-mi/'
    | '/para-ayudar/entrenamiento/$mid'
    | '/para-ayudar/entrenamiento/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AyudaRoute: typeof AyudaRoute
  ContactoRoute: typeof ContactoRoute
  FuentesRoute: typeof FuentesRoute
  ParaAyudarRoute: typeof ParaAyudarRouteWithChildren
  ParaMiRoute: typeof ParaMiRouteWithChildren
  PrivacidadRoute: typeof PrivacidadRoute
  RedRoute: typeof RedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/red': {
      id: '/red'
      path: '/red'
      fullPath: '/red'
      preLoaderRoute: typeof RedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para-mi': {
      id: '/para-mi'
      path: '/para-mi'
      fullPath: '/para-mi'
      preLoaderRoute: typeof ParaMiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para-ayudar': {
      id: '/para-ayudar'
      path: '/para-ayudar'
      fullPath: '/para-ayudar'
      preLoaderRoute: typeof ParaAyudarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fuentes': {
      id: '/fuentes'
      path: '/fuentes'
      fullPath: '/fuentes'
      preLoaderRoute: typeof FuentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayuda': {
      id: '/ayuda'
      path: '/ayuda'
      fullPath: '/ayuda'
      preLoaderRoute: typeof AyudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para-mi/': {
      id: '/para-mi/'
      path: '/'
      fullPath: '/para-mi/'
      preLoaderRoute: typeof ParaMiIndexRouteImport
      parentRoute: typeof ParaMiRoute
    }
    '/para-ayudar/': {
      id: '/para-ayudar/'
      path: '/'
      fullPath: '/para-ayudar/'
      preLoaderRoute: typeof ParaAyudarIndexRouteImport
      parentRoute: typeof ParaAyudarRoute
    }
    '/para-mi/respira': {
      id: '/para-mi/respira'
      path: '/respira'
      fullPath: '/para-mi/respira'
      preLoaderRoute: typeof ParaMiRespiraRouteImport
      parentRoute: typeof ParaMiRoute
    }
    '/para-mi/replicas': {
      id: '/para-mi/replicas'
      path: '/replicas'
      fullPath: '/para-mi/replicas'
      preLoaderRoute: typeof ParaMiReplicasRouteImport
      parentRoute: typeof ParaMiRoute
    }
    '/para-mi/presente': {
      id: '/para-mi/presente'
      path: '/presente'
      fullPath: '/para-mi/presente'
      preLoaderRoute: typeof ParaMiPresenteRouteImport
      parentRoute: typeof ParaMiRoute
    }
    '/para-mi/perdiste-todo': {
      id: '/para-mi/perdiste-todo'
      path: '/perdiste-todo'
      fullPath: '/para-mi/perdiste-todo'
      preLoaderRoute: typeof ParaMiPerdisteTodoRouteImport
      parentRoute: typeof ParaMiRoute
    }
    '/para-mi/noticias': {
      id: '/para-mi/noticias'
      path: '/noticias'
      fullPath: '/para-mi/noticias'
      preLoaderRoute: typeof ParaMiNoticiasRouteImport
      parentRoute: typeof ParaMiRoute
    }
    '/para-mi/normal': {
      id: '/para-mi/normal'
      path: '/normal'
      fullPath: '/para-mi/normal'
      preLoaderRoute: typeof ParaMiNormalRouteImport
      parentRoute: typeof ParaMiRoute
    }
    '/para-mi/no-encontrado': {
      id: '/para-mi/no-encontrado'
      path: '/no-encontrado'
      fullPath: '/para-mi/no-encontrado'
      preLoaderRoute: typeof ParaMiNoEncontradoRouteImport
      parentRoute: typeof ParaMiRoute
    }
    '/para-mi/lejos': {
      id: '/para-mi/lejos'
      path: '/lejos'
      fullPath: '/para-mi/lejos'
      preLoaderRoute: typeof ParaMiLejosRouteImport
      parentRoute: typeof ParaMiRoute
    }
    '/para-mi/duelo': {
      id: '/para-mi/duelo'
      path: '/duelo'
      fullPath: '/para-mi/duelo'
      preLoaderRoute: typeof ParaMiDueloRouteImport
      parentRoute: typeof ParaMiRoute
    }
    '/para-mi/diario': {
      id: '/para-mi/diario'
      path: '/diario'
      fullPath: '/para-mi/diario'
      preLoaderRoute: typeof ParaMiDiarioRouteImport
      parentRoute: typeof ParaMiRoute
    }
    '/para-mi/descansar': {
      id: '/para-mi/descansar'
      path: '/descansar'
      fullPath: '/para-mi/descansar'
      preLoaderRoute: typeof ParaMiDescansarRouteImport
      parentRoute: typeof ParaMiRoute
    }
    '/para-mi/como-estas': {
      id: '/para-mi/como-estas'
      path: '/como-estas'
      fullPath: '/para-mi/como-estas'
      preLoaderRoute: typeof ParaMiComoEstasRouteImport
      parentRoute: typeof ParaMiRoute
    }
    '/para-ayudar/que-decir': {
      id: '/para-ayudar/que-decir'
      path: '/que-decir'
      fullPath: '/para-ayudar/que-decir'
      preLoaderRoute: typeof ParaAyudarQueDecirRouteImport
      parentRoute: typeof ParaAyudarRoute
    }
    '/para-ayudar/panico': {
      id: '/para-ayudar/panico'
      path: '/panico'
      fullPath: '/para-ayudar/panico'
      preLoaderRoute: typeof ParaAyudarPanicoRouteImport
      parentRoute: typeof ParaAyudarRoute
    }
    '/para-ayudar/no-mejora': {
      id: '/para-ayudar/no-mejora'
      path: '/no-mejora'
      fullPath: '/para-ayudar/no-mejora'
      preLoaderRoute: typeof ParaAyudarNoMejoraRouteImport
      parentRoute: typeof ParaAyudarRoute
    }
    '/para-ayudar/nino': {
      id: '/para-ayudar/nino'
      path: '/nino'
      fullPath: '/para-ayudar/nino'
      preLoaderRoute: typeof ParaAyudarNinoRouteImport
      parentRoute: typeof ParaAyudarRoute
    }
    '/para-ayudar/entrenamiento': {
      id: '/para-ayudar/entrenamiento'
      path: '/entrenamiento'
      fullPath: '/para-ayudar/entrenamiento'
      preLoaderRoute: typeof ParaAyudarEntrenamientoRouteImport
      parentRoute: typeof ParaAyudarRoute
    }
    '/para-ayudar/ahora': {
      id: '/para-ayudar/ahora'
      path: '/ahora'
      fullPath: '/para-ayudar/ahora'
      preLoaderRoute: typeof ParaAyudarAhoraRouteImport
      parentRoute: typeof ParaAyudarRoute
    }
    '/para-ayudar/adulto-mayor': {
      id: '/para-ayudar/adulto-mayor'
      path: '/adulto-mayor'
      fullPath: '/para-ayudar/adulto-mayor'
      preLoaderRoute: typeof ParaAyudarAdultoMayorRouteImport
      parentRoute: typeof ParaAyudarRoute
    }
    '/para-ayudar/a-distancia': {
      id: '/para-ayudar/a-distancia'
      path: '/a-distancia'
      fullPath: '/para-ayudar/a-distancia'
      preLoaderRoute: typeof ParaAyudarADistanciaRouteImport
      parentRoute: typeof ParaAyudarRoute
    }
    '/para-ayudar/entrenamiento/': {
      id: '/para-ayudar/entrenamiento/'
      path: '/'
      fullPath: '/para-ayudar/entrenamiento/'
      preLoaderRoute: typeof ParaAyudarEntrenamientoIndexRouteImport
      parentRoute: typeof ParaAyudarEntrenamientoRoute
    }
    '/para-ayudar/entrenamiento/$mid': {
      id: '/para-ayudar/entrenamiento/$mid'
      path: '/$mid'
      fullPath: '/para-ayudar/entrenamiento/$mid'
      preLoaderRoute: typeof ParaAyudarEntrenamientoMidRouteImport
      parentRoute: typeof ParaAyudarEntrenamientoRoute
    }
  }
}

interface ParaAyudarEntrenamientoRouteChildren {
  ParaAyudarEntrenamientoMidRoute: typeof ParaAyudarEntrenamientoMidRoute
  ParaAyudarEntrenamientoIndexRoute: typeof ParaAyudarEntrenamientoIndexRoute
}

const ParaAyudarEntrenamientoRouteChildren: ParaAyudarEntrenamientoRouteChildren =
  {
    ParaAyudarEntrenamientoMidRoute: ParaAyudarEntrenamientoMidRoute,
    ParaAyudarEntrenamientoIndexRoute: ParaAyudarEntrenamientoIndexRoute,
  }

const ParaAyudarEntrenamientoRouteWithChildren =
  ParaAyudarEntrenamientoRoute._addFileChildren(
    ParaAyudarEntrenamientoRouteChildren,
  )

interface ParaAyudarRouteChildren {
  ParaAyudarADistanciaRoute: typeof ParaAyudarADistanciaRoute
  ParaAyudarAdultoMayorRoute: typeof ParaAyudarAdultoMayorRoute
  ParaAyudarAhoraRoute: typeof ParaAyudarAhoraRoute
  ParaAyudarEntrenamientoRoute: typeof ParaAyudarEntrenamientoRouteWithChildren
  ParaAyudarNinoRoute: typeof ParaAyudarNinoRoute
  ParaAyudarNoMejoraRoute: typeof ParaAyudarNoMejoraRoute
  ParaAyudarPanicoRoute: typeof ParaAyudarPanicoRoute
  ParaAyudarQueDecirRoute: typeof ParaAyudarQueDecirRoute
  ParaAyudarIndexRoute: typeof ParaAyudarIndexRoute
}

const ParaAyudarRouteChildren: ParaAyudarRouteChildren = {
  ParaAyudarADistanciaRoute: ParaAyudarADistanciaRoute,
  ParaAyudarAdultoMayorRoute: ParaAyudarAdultoMayorRoute,
  ParaAyudarAhoraRoute: ParaAyudarAhoraRoute,
  ParaAyudarEntrenamientoRoute: ParaAyudarEntrenamientoRouteWithChildren,
  ParaAyudarNinoRoute: ParaAyudarNinoRoute,
  ParaAyudarNoMejoraRoute: ParaAyudarNoMejoraRoute,
  ParaAyudarPanicoRoute: ParaAyudarPanicoRoute,
  ParaAyudarQueDecirRoute: ParaAyudarQueDecirRoute,
  ParaAyudarIndexRoute: ParaAyudarIndexRoute,
}

const ParaAyudarRouteWithChildren = ParaAyudarRoute._addFileChildren(
  ParaAyudarRouteChildren,
)

interface ParaMiRouteChildren {
  ParaMiComoEstasRoute: typeof ParaMiComoEstasRoute
  ParaMiDescansarRoute: typeof ParaMiDescansarRoute
  ParaMiDiarioRoute: typeof ParaMiDiarioRoute
  ParaMiDueloRoute: typeof ParaMiDueloRoute
  ParaMiLejosRoute: typeof ParaMiLejosRoute
  ParaMiNoEncontradoRoute: typeof ParaMiNoEncontradoRoute
  ParaMiNormalRoute: typeof ParaMiNormalRoute
  ParaMiNoticiasRoute: typeof ParaMiNoticiasRoute
  ParaMiPerdisteTodoRoute: typeof ParaMiPerdisteTodoRoute
  ParaMiPresenteRoute: typeof ParaMiPresenteRoute
  ParaMiReplicasRoute: typeof ParaMiReplicasRoute
  ParaMiRespiraRoute: typeof ParaMiRespiraRoute
  ParaMiIndexRoute: typeof ParaMiIndexRoute
}

const ParaMiRouteChildren: ParaMiRouteChildren = {
  ParaMiComoEstasRoute: ParaMiComoEstasRoute,
  ParaMiDescansarRoute: ParaMiDescansarRoute,
  ParaMiDiarioRoute: ParaMiDiarioRoute,
  ParaMiDueloRoute: ParaMiDueloRoute,
  ParaMiLejosRoute: ParaMiLejosRoute,
  ParaMiNoEncontradoRoute: ParaMiNoEncontradoRoute,
  ParaMiNormalRoute: ParaMiNormalRoute,
  ParaMiNoticiasRoute: ParaMiNoticiasRoute,
  ParaMiPerdisteTodoRoute: ParaMiPerdisteTodoRoute,
  ParaMiPresenteRoute: ParaMiPresenteRoute,
  ParaMiReplicasRoute: ParaMiReplicasRoute,
  ParaMiRespiraRoute: ParaMiRespiraRoute,
  ParaMiIndexRoute: ParaMiIndexRoute,
}

const ParaMiRouteWithChildren =
  ParaMiRoute._addFileChildren(ParaMiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AyudaRoute: AyudaRoute,
  ContactoRoute: ContactoRoute,
  FuentesRoute: FuentesRoute,
  ParaAyudarRoute: ParaAyudarRouteWithChildren,
  ParaMiRoute: ParaMiRouteWithChildren,
  PrivacidadRoute: PrivacidadRoute,
  RedRoute: RedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
